//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Managers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public Manager()
        {
            this.SaleInfo = new HashSet<SaleInfo>();
        }
    
        public int ID_Manager { get; set; }
        public string ManagerName { get; set; }
    
        public virtual ICollection<SaleInfo> SaleInfo { get; set; }
    }
}
